defaults:
  host: 'https://en.wikipedia.org/'
  path: '/w/api.php'
revisions:
  params:
    action: query
    prop: revisions
    format: json
    rvlimit: 500
    # titles: Trie
    rvprop:
    - ids
    - timestamp
    - user
    - size
    - comment
    - parsedcomment
    - content
    - parsetree
source:
  params:
    action: parse
    format: json
    # page: Trie
    prop:
    - text
    - langlinks
    - categories
    - categorieshtml
    - links
    - templates
    - images
    - externallinks
    - sections
    - revid
    - displaytitle
    - headitems
    - headhtml
    - wikitext
    - properties
    - parsetree
