revisions:
  host: 'https://en.wikipedia.org/'
  path: '/w/api.php'
  params:
    action: query
    prop: revisions
    format: json
    rvlimit: 500
    #titles: Trie
    rvprop:
    - ids
    - timestamp
    - user
    - size
    - comment
    - parsedcomment
    - content
    - parsetree

